export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_FAIL = 'GOOGLE_SIGN_IN_FAIL';

export const ANONYMOUS_SIGN_IN_START = 'ANONYMOUS_SIGN_IN_START';
export const ANONYMOUS_SIGN_IN_SUCCESS = 'ANONYMOUS_SIGN_IN_SUCCESS';
export const ANONYMOUS_SIGN_IN_FAIL = 'ANONYMOUS_SIGN_IN_FAIL';

export const SET_USER = 'SET_USER'

export const SET_USER_STATUS = 'SET_USER_STATUS'

export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS'